version: '3.5'
services:
  postgres:
    image: postgres:12
    volumes:
      - ./local/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file: ./.postgres-env
    environment:
      POSTGRES_USER: ganbatte
  frontend:
    build:
      context: .
      target: frontend
    ports:
      - 3000:5173
    volumes:
      - ./frontend/src:/app/frontend/src
  server:
    depends_on:
      - postgres
    build:
      context: .
      target: server
    environment:
      NO_DOTENV: 'true'
    volumes:
      - ./server/src:/app/server/src
    ports:
      - 3001:3000
